services:
  kafka:
    image: confluentinc/cp-kafka:7.9.1
    container_name: kafka
    hostname: kafka
    restart: always
    ports:
      - 9092:9092
      - 9093:9093
      - 9094:9094
    environment:
      CLUSTER_ID: kafka_cluster
      KAFKA_KRAFT_MODE: "true"
      KAFKA_CLUSTER_ID: cluster1
      KAFKA_PROCESS_ROLES: controller,broker
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@localhost:9094"

      #KAFKA_LOG4J_ROOT_LOGLEVEL: DEBUG

      # Don't use SSL in advertising listeners, cause a bug in configure: https://github.com/apache/kafka/blob/trunk/docker/resources/common-scripts/configure
      KAFKA_ADVERTISED_LISTENERS: "TLS://${KAFKA_HOST}:9092,PLAINTEXT_HOST://${KAFKA_HOST}:9093"
      KAFKA_LISTENERS: "TLS://:9092,PLAINTEXT_HOST://:9093,CONTROLLER://:9094"
      KAFKA_INTER_BROKER_LISTENER_NAME: TLS
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "TLS:SSL,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT"
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      KAFKA_SSL_KEYSTORE_LOCATION: /etc/kafka/secrets/fullchain.pem
      KAFKA_SSL_KEYSTORE_TYPE: PEM
      KAFKA_SSL_TRUSTSTORE_LOCATION: /etc/kafka/secrets/rootCA.pem
      KAFKA_SSL_TRUSTSTORE_TYPE: PEM
 
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_MESSAGE_MAX_BYTES: 10485880
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: "1"
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
    volumes:
      - cert/fullchain.pem:/etc/kafka/secrets/fullchain.pem
      - cert/rootCA.pem:/etc/kafka/secrets/rootCA.pem
        
